[flake]
scope = "full"
mode = "custom"
backend = "py-harbor"

[flake.expected_outputs]
packages = [
  "canscribe-cpu",
  "docs",
  "site",
]
apps = ["canscribe-cpu"]
dev_shells = [
  "cpu",
  "docs",
  "nvidia",
  "amd",
  "apple",
  "site",
]
checks = [
  "flake-eval",
  "offline-tests",
  "typecheck",
  "uv-format",
]

[ci]
runtime = "nix"
runner = "codeberg-medium"
with_pypi_publish = true
provider = "actions"
platform = "forgejo"

[ci.pages]
repo = "caniko/canscribe"
token_secret = "CODEBERG_TOKEN"
source_branch = "mvp"
